Fix method for parsing received messages with aggregated payload
astarte-platform/astarte-device-sdk-csharp pull request #39
Opened 2023-06-06 07:27 UTC by osmanhadzic

Closes: #35

2023-06-06 09:27 UTC, harlem88 requested changes

2023-06-06 09:27 UTC, harlem88 commented on CHANGELOG.md
> +- Fix method for parsing received messages with aggregated payload.
```suggestion
- Fix parsing issue when receiving an aggregate object payload.
```

2023-06-06 09:30 UTC, harlem88 commented
Fix typo in the first commit `Fix object seserialize in Build method` -> `Fix object deserialization in Build method`

2023-06-07 10:23 UTC, nedimtokic approved these changes

2023-06-07 10:46 UTC, harlem88 approved these changes

2023-06-07 10:47 UTC, merged