Implement fallout strategy failed individual message
astarte-platform/astarte-device-sdk-csharp pull request #59
Opened 2024-01-31 13:33 UTC by osmanhadzic

Astarte Device SDK does not currently implement a fallout strategy for individual datastream messages.

In the 'Class AstarteMqttV1Transport,' the method 'SendIndividualValue' handles the 'MqttCommunicationException' by calling the method 'HandleDatastreamFailedPublish' for the stored message.

When the device loses connection with Astarte, failed individual datastream messages will be stored. The method of storage can be determined from a mapping of the interface field 'Retention.' Retention types include 'volatile,' which is stored in cache memory, and 'stored,' which is saved in the local database. The default retention value is 'discarded,' and the 'discard' message retention type does not save.

Testing:

1. Set up the device to send individual datastream messages with the interface mapping set to 'volatile' or 'stored.'
2. Turn off the network on the device.
3. Wait until the device loses connection to Astarte.
4. Turn on the network on the device.

Finally, failed messages will be sent to Astarte.

2024-02-01 14:25 UTC, nedimtokic approved these changes
Tested on debug mode, `stored` data can be found in sqLite database. After reconnect data are sent to the Astarte.

2024-02-01 15:26 UTC, harlem88 approved these changes

2024-02-01 15:28 UTC, harlem88 commented
Report this change also to the Changelog

2024-02-05 07:06 UTC, harlem88 requested changes

2024-02-05 07:06 UTC, harlem88 commented on CHANGELOG.md
> +## [0.6.1] - Unreleased
```suggestion
## [0.7.0] - Unreleased
```

2024-02-05 16:38 UTC, harlem88 approved these changes

2024-02-05 16:38 UTC, merged